- name: Setup Frontend
  hosts: all
  become: yes
  tasks:
    - name: Installing Nginx Server
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Remove directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download and Extract Frontend Content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copying Roboshop Configuration File
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc//nginx/default.d/roboshop.conf

    - name: Starting Nginx Server
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
        enabled: true








#  # we need to copy config file
#  echo -e "${color}Copying Roboshop Configuration File${nocolor}"
#  cp /root/roboshop-shell/roboshop.conf /etc//nginx/default.d/roboshop.conf &>>${log_file}
#  stat_check $?
#  
#  echo -e "${color}Starting Nginx Server${nocolor}"
#  systemctl enable nginx &>>${log_file}
#  systemctl restart nginx &>>${log_file}
#  stat_check $?